species:
  heterozygosity: 0.001
  ploidy:
    male:
      all: 2
      Y: 1
      X: 1
    female:
      all: 2
      X: 2
      Y: 0

samples:
  x:
    resolution: 0.1
    universe: "[0.0,1.0]"
    sex: female
    somatic-effective-mutation-rate: 4.4e-7
  y:
    resolution: 0.1
    universe: "[0.0,1.0]"
    sex: female
    somatic-effective-mutation-rate: 4.4e-7


events:
  x: "x:]0.0,1.0] & y:0.0"
  y: "y:]0.0,1.0] & x:0.0"
  both: "y:]0.0,1.0] & x:]0.0,1.0]"
